In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
import math

In [2]:
snp = pd.read_csv('S&P500.csv',parse_dates=True, index_col='Date')
snp_ret = np.log(snp/snp.shift(1))
snp_ret

               Close
Date
2016-11-15       NaN
2016-11-16 -0.001584
2016-11-17  0.004665
2016-11-18 -0.002390
2016-11-21  0.007434
...              ...
2019-11-08  0.002557
2019-11-11 -0.001964
2019-11-12  0.001563
2019-11-13  0.000711
2019-11-14  0.000837

[755 rows x 1 columns]

In [3]:
#1 S&P Annual Volatility
annual_vol = snp_ret.std() * np.sqrt(252)
annual_vol[0]

0.12831845548060564

# Black Scholes Merton Model

In [4]:
t = 1/12
so = snp.Close[-1]
k = 3100
q =.023
rf = 0.05
vol = annual_vol[0]



def blackscholes(option,so,k,rf,t,vol,div=0):
    d1 = (np.log(so/k)+(rf-div+vol**2/2)*t)/(vol*np.sqrt(t))
    d2 = d1-vol*np.sqrt(t)
    if option == 'call':
        call = so*math.e**(-div*t) * norm.cdf(d1) - k*math.e**(-rf*t) * norm.cdf(d2)
        return call
    elif option == 'put':
        put = k*math.e**(-rf*t)*norm.cdf(-d2) - so*math.e**(-div*t)*norm.cdf(-d1)
        return put

In [5]:
cboe = blackscholes('call',so,k,rf,t,vol,q)
print(f'Value of CBOE Option: {cboe*100}')

Value of CBOE Option: 4746.202827704724

In [6]:
np.random.normal()
so
vol

0.12831845548060564

# Monte Carlo

In [7]:
# so = 10
# k = 9.5
# vol = 0.2
# r = 0.05
# t=0.5


mc = pd.DataFrame({'counter': range(1,1001,1),'norm' : np.random.normal(size=(1000))})
mc

     counter      norm
0          1 -1.901435
1          2 -1.739621
2          3 -0.506636
3          4  0.353588
4          5 -0.578008
..       ...       ...
995      996  0.009550
996      997  0.201052
997      998 -1.342794
998      999 -0.007624
999     1000  0.436125

[1000 rows x 2 columns]

In [8]:
mc['Gross_return'] = math.e**((rf-q-.5*vol**2)*t + vol * np.sqrt(t)*mc.norm)

In [15]:
mc['Price'] = mc.Gross_return * so
mc['Payoff'] = np.where(mc.Price > k, mc.Price - k, 0)
mc['fi'] = math.e**(-rf*t) * mc.Payoff
mc.head()

   counter      norm  Gross_return        Price     Payoff         fi
0        1 -1.901435      0.933448  2890.543947   0.000000   0.000000
1        2 -1.739621      0.939060  2907.921821   0.000000   0.000000
2        3 -0.506636      0.982944  3043.814024   0.000000   0.000000
3        4  0.353588      1.014770  3142.366085  42.366085  42.189927
4        5 -0.578008      0.980349  3035.777468   0.000000   0.000000

In [16]:
std_error = mc.fi.std()/np.sqrt(mc.shape[0])
std_error

2.1280363816468837

In [17]:
pv_mean = mc.fi.mean()
print(f'PV Mean: {pv_mean}')
option_val = pv_mean * 100
print(f'Option Value: {option_val}')
ciu = option_val + (1.96 * std_error) * 100
cid = option_val - (1.96 * std_error) * 100
print(f'Confidence Interval: ({cid}, {ciu})')

PV Mean: 46.44060713211742
Option Value: 4644.060713211742
Confidence Interval: (4226.965582408953, 5061.155844014531)

# Asian European Option

In [18]:
# 3/21
asian = pd.DataFrame({'counter': range(1,1001)}).set_index('counter')
asian['n1'] = np.random.normal(size=(1000))
asian['g1'] = math.e**((rf-q-.5*vol**2)*(t/21) + vol * np.sqrt(t/21)*asian['n1'])
asian['p1'] = asian['g1'] * so
for i in range(2,22,1):
    asian[f'n{i}'] = np.random.normal(size=(1000))
    asian[f'g{i}'] = math.e**((rf-q-.5*vol**2)*(t/21) + vol * np.sqrt(t/21)*asian[f'n{i}'])
    asian[f'p{i}'] = asian[f'g{i}'] * asian[f'p{i-1}']
asian

,n1,g1,p1,n2,g2,p2,n3,g3,p3,n4,...,p18,n19,g19,p19,n20,g20,p20,n21,g21,p21
counter,,,,,,,,,,,,,,,,,,,,,
1,0.856910,1.007026,3118.385870,0.884786,1.007253,3141.002402,-0.614059,0.995123,3125.683046,0.628592,...,3340.046899,-1.104200,0.991188,3310.614235,-0.177256,0.998643,3306.120347,0.246235,1.002067,3312.954095
2,-0.652283,0.994815,3080.574959,2.148095,1.017591,3134.765682,0.178717,1.001520,3139.531302,0.356517,...,3302.868063,-1.530007,0.987782,3262.514335,0.658808,1.005414,3280.178975,-1.340473,0.989297,3245.070286
3,0.797483,1.006542,3116.888262,-2.031361,0.983787,3066.354875,2.088370,1.017100,3118.789423,-2.182300,...,3030.842832,0.150407,1.001291,3034.755925,-1.524733,0.987824,2997.805731,0.276990,1.002316,3004.749085
4,0.400884,1.003320,3106.912054,-0.769366,0.993874,3087.880010,1.430893,1.011709,3124.035474,-0.216728,...,3187.460851,-1.925566,0.984629,3138.466064,-0.391456,0.996915,3128.783855,1.168524,1.009565,3158.712120
5,-0.878459,0.992998,3074.948062,0.696383,1.005720,3092.536289,-0.086176,0.999378,3090.612975,0.258083,...,2959.488340,-0.996305,0.992053,2935.968645,-1.589490,0.987307,2898.703515,1.293419,1.010585,2929.386882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,-0.513717,0.995930,3084.027363,0.055839,1.000526,3085.649483,0.209986,1.001773,3091.121636,1.109698,...,3100.442846,0.671678,1.005519,3117.554256,-0.226239,0.998247,3112.089964,0.042562,1.000419,3113.392680
997,-0.820966,0.993460,3076.377406,0.734041,1.006026,3094.915765,-1.442840,0.988478,3059.257534,-0.561343,...,3030.006068,1.842666,1.015082,3075.704332,0.496356,1.004095,3088.299429,-0.533917,0.995768,3075.228629
998,-2.666678,0.978748,3030.820248,0.774125,1.006352,3050.072169,-0.651557,0.994821,3034.276442,0.751247,...,2967.800849,1.236832,1.010123,2997.844065,-0.214559,0.998342,2992.872142,0.856590,1.007023,3013.891364
999,-1.002330,0.992004,3071.870700,-0.876743,0.993012,3050.404550,0.172783,1.001472,3054.895389,0.494545,...,3031.808484,0.552195,1.004548,3045.598201,0.745598,1.006120,3064.237316,0.335252,1.002788,3072.781307
1000,1.407447,1.011517,3132.294108,-0.780703,0.993783,3112.821309,1.417244,1.011597,3148.921372,1.323081,...,3180.998377,0.295147,1.002463,3188.834018,0.271552,1.002272,3196.079333,-0.652491,0.994814,3179.503454

In [19]:
filter_col = [col for col in asian if col.startswith('p')]
p = asian[filter_col]
asian['Avg Price'] = p.mean(axis=1)
asian['Payoff'] = np.where(asian['Avg Price'] > k, asian['Avg Price'] - k,0)
asian['PV'] = math.e**(-rf*t) * asian.Payoff
asian

,n1,g1,p1,n2,g2,p2,n3,g3,p3,n4,...,p19,n20,g20,p20,n21,g21,p21,Avg Price,Payoff,PV
counter,,,,,,,,,,,,,,,,,,,,,
1,0.856910,1.007026,3118.385870,0.884786,1.007253,3141.002402,-0.614059,0.995123,3125.683046,0.628592,...,3310.614235,-0.177256,0.998643,3306.120347,0.246235,1.002067,3312.954095,3230.935203,130.935203,130.390775
2,-0.652283,0.994815,3080.574959,2.148095,1.017591,3134.765682,0.178717,1.001520,3139.531302,0.356517,...,3262.514335,0.658808,1.005414,3280.178975,-1.340473,0.989297,3245.070286,3230.966372,130.966372,130.421814
3,0.797483,1.006542,3116.888262,-2.031361,0.983787,3066.354875,2.088370,1.017100,3118.789423,-2.182300,...,3034.755925,-1.524733,0.987824,2997.805731,0.276990,1.002316,3004.749085,3029.512486,0.000000,0.000000
4,0.400884,1.003320,3106.912054,-0.769366,0.993874,3087.880010,1.430893,1.011709,3124.035474,-0.216728,...,3138.466064,-0.391456,0.996915,3128.783855,1.168524,1.009565,3158.712120,3160.265293,60.265293,60.014710
5,-0.878459,0.992998,3074.948062,0.696383,1.005720,3092.536289,-0.086176,0.999378,3090.612975,0.258083,...,2935.968645,-1.589490,0.987307,2898.703515,1.293419,1.010585,2929.386882,3012.596860,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,-0.513717,0.995930,3084.027363,0.055839,1.000526,3085.649483,0.209986,1.001773,3091.121636,1.109698,...,3117.554256,-0.226239,0.998247,3112.089964,0.042562,1.000419,3113.392680,3096.200613,0.000000,0.000000
997,-0.820966,0.993460,3076.377406,0.734041,1.006026,3094.915765,-1.442840,0.988478,3059.257534,-0.561343,...,3075.704332,0.496356,1.004095,3088.299429,-0.533917,0.995768,3075.228629,3053.184260,0.000000,0.000000
998,-2.666678,0.978748,3030.820248,0.774125,1.006352,3050.072169,-0.651557,0.994821,3034.276442,0.751247,...,2997.844065,-0.214559,0.998342,2992.872142,0.856590,1.007023,3013.891364,3029.279575,0.000000,0.000000
999,-1.002330,0.992004,3071.870700,-0.876743,0.993012,3050.404550,0.172783,1.001472,3054.895389,0.494545,...,3045.598201,0.745598,1.006120,3064.237316,0.335252,1.002788,3072.781307,3017.231002,0.000000,0.000000
1000,1.407447,1.011517,3132.294108,-0.780703,0.993783,3112.821309,1.417244,1.011597,3148.921372,1.323081,...,3188.834018,0.271552,1.002272,3196.079333,-0.652491,0.994814,3179.503454,3171.890413,71.890413,71.591493

In [20]:
pv_mean = asian.PV.mean()
print(f'PV Mean: {pv_mean}]')
std_error_a = asian.PV.std()/np.sqrt(asian.shape[0])
opt_val = pv_mean * 100
print(f'Option Value: {opt_val}')
ciua = opt_val + (1.96 * std_error_a) * 100
cida = opt_val - (1.96 * std_error_a) * 100
print(f'Confidence Interval: ({cida}, {ciua})')

PV Mean: 27.579024931211222]
Option Value: 2757.9024931211225
Confidence Interval: (2504.356315414695, 3011.44867082755)

# Binomial Tree

In [21]:
# Binomial Tree
up = math.e**(vol*np.sqrt(t/3))
down = 1/up
so
pu = (math.e**((rf-q)*t/3) - down)/(up - down)
pd = (1-pu)
vu = so * up
vd = so * down
vuu = vu * up
vud = vu * down
vdd = vd * down

vuuu = vuu * up
vuud = vuu * down
vudd = vud * down
vddd = vdd * down

ruuu = vuuu - k
ruud = vuud - k

puuu = pu * pu * pu
puud = 3*pu*pu*pd

In [ ]:
print(vuuu, vuud, vudd, vddd)
v1 = ruuu * puuu
v2 = ruud * puud
f1 = v1 + v2
value_call = f1* math.e ** (-rf*t)
print(f'Value of Call: {value_call}')
print(f'Value of Option: {value_call*100}')

In [ ]:
import matplotlib.dates as mdates
# ann_ts_ret.plot(kind='bar')
# plt.bar(x=ann_ts_ret.index, height = ann_ts_ret.tsret,data=ann_ts_ret)
years = mdates.YearLocator()   # every year
months = mdates.MonthLocator()  # every month
years_fmt = mdates.DateFormatter('%Y')

fig, ax = plt.subplots()

# sns.barplot(ann_ts_ret.index,ann_ts_ret.tsret, data=ann_ts_ret, ax=ax1)
ax.plot(ann_ts_ret.index,ann_ts_ret.tsret)

ax.xaxis.set_major_locator(years)
ax.xaxis.set_major_formatter(years_fmt)
ax.xaxis.set_minor_locator(months)

# plt.xticks([])


# plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
# # plt.plot(days,y)
# plt.gcf().autofmt_xdate()
plt.gca().xaxis.set_major_locator(mdates.YearLocator(5))

# plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%m/%d/%Y'))
# plt.gca().xaxis.set_major_locator(mdates.YearLocator())
# plt.gcf().autofmt_xdate()
# plt.fmt_xdata = mdates.DateFormatter('%Y')

# plt.show()
# ann_ts_ret.tsret

In [ ]:
# plt.cgf()
# plt.gca()
# ax.set_title()
# ax.set_xlabel()
# ax.set_ylabel()
# fig, ax = plt.subplots()
fig, (ax1, ax2) = plt.subplots(nrows=2,ncols=2)
ddd

In [40]:
norm.ppf(.95)

1.6448536269514722

In [72]:
pup = (1 - .85)/(1.1-.85)
pdo = 1 - pup
# vvv = (pup * 11) * math.e **(-.06 * .5)
# vdd = pdo * 1
# vew = vvv + vdd
# vew * math.e**(-.06 * .5)
# pup
# pdo
# vvv
((11*pup) + (1*pdo)) * math.e **(-.06 * .5)

6.793118734839556

In [71]:
# Q3
vvv + (((pdo * 1) * math.e **(-.06 * .5)))

6.793118734839556

In [52]:
# Practice for Deriv
t = 6/12
so = 30 - (3 *math.e **(-.06*3/12))
k = 29
# q =.023
rf = 0.06
vol = .4

##Q4

# def blackscholes(option,so,k,rf,t,vol,div=0):
#     d1 = (np.log(so/k)+(rf-div+vol**2/2)*t)/(vol*np.sqrt(t))
#     d2 = d1-vol*np.sqrt(t)
#     if option == 'call':
#         call = so*math.e**(-div*t) * norm.cdf(d1) - k*math.e**(-rf*t) * norm.cdf(d2)
#         return call
#     elif option == 'put':
#         put = k*math.e**(-rf*t)*norm.cdf(-d2) - so*math.e**(-div*t)*norm.cdf(-d1)
#         return put

blackscholes('call',so,k,rf,t,vol)

2.5846231998006886